//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.27 at 07:05:16 PM CEST 
//


package com.eureka.model.eurekamodel.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://www.ftn.uns.ac.rs/megatravel}soap_status"/>
 *         &lt;element name="messaggeId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "messaggeId"
})
@XmlRootElement(name = "message_response")
public class MessageResponse {

    @XmlElement(required = true)
    protected SoapStatus status;
    protected long messaggeId;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link SoapStatus }
     *     
     */
    public SoapStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoapStatus }
     *     
     */
    public void setStatus(SoapStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the messaggeId property.
     * 
     */
    public long getMessaggeId() {
        return messaggeId;
    }

    /**
     * Sets the value of the messaggeId property.
     * 
     */
    public void setMessaggeId(long value) {
        this.messaggeId = value;
    }

}
