//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.27 at 07:05:16 PM CEST 
//


package com.eureka.model.eurekamodel.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.megatravel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.megatravel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAgentRequest }
     * 
     */
    public GetAgentRequest createGetAgentRequest() {
        return new GetAgentRequest();
    }

    /**
     * Create an instance of {@link GetReservationResponse }
     * 
     */
    public GetReservationResponse createGetReservationResponse() {
        return new GetReservationResponse();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link GetMessageResponse }
     * 
     */
    public GetMessageResponse createGetMessageResponse() {
        return new GetMessageResponse();
    }

    /**
     * Create an instance of {@link Messagge }
     * 
     */
    public Messagge createMessagge() {
        return new Messagge();
    }

    /**
     * Create an instance of {@link GetAccommodationServiceResponse }
     * 
     */
    public GetAccommodationServiceResponse createGetAccommodationServiceResponse() {
        return new GetAccommodationServiceResponse();
    }

    /**
     * Create an instance of {@link AccommodationService }
     * 
     */
    public AccommodationService createAccommodationService() {
        return new AccommodationService();
    }

    /**
     * Create an instance of {@link GetRatingRequest }
     * 
     */
    public GetRatingRequest createGetRatingRequest() {
        return new GetRatingRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationTypeRequest }
     * 
     */
    public GetAccommodationTypeRequest createGetAccommodationTypeRequest() {
        return new GetAccommodationTypeRequest();
    }

    /**
     * Create an instance of {@link AddImagesRequest }
     * 
     */
    public AddImagesRequest createAddImagesRequest() {
        return new AddImagesRequest();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link ReservationRequest }
     * 
     */
    public ReservationRequest createReservationRequest() {
        return new ReservationRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationServiceRequest }
     * 
     */
    public GetAccommodationServiceRequest createGetAccommodationServiceRequest() {
        return new GetAccommodationServiceRequest();
    }

    /**
     * Create an instance of {@link AddPriceResponse }
     * 
     */
    public AddPriceResponse createAddPriceResponse() {
        return new AddPriceResponse();
    }

    /**
     * Create an instance of {@link GetRecensionRequest }
     * 
     */
    public GetRecensionRequest createGetRecensionRequest() {
        return new GetRecensionRequest();
    }

    /**
     * Create an instance of {@link AddAccommodationRequest }
     * 
     */
    public AddAccommodationRequest createAddAccommodationRequest() {
        return new AddAccommodationRequest();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link ReservationResponse }
     * 
     */
    public ReservationResponse createReservationResponse() {
        return new ReservationResponse();
    }

    /**
     * Create an instance of {@link ApproveReservationRequest }
     * 
     */
    public ApproveReservationRequest createApproveReservationRequest() {
        return new ApproveReservationRequest();
    }

    /**
     * Create an instance of {@link ApproveReservationResponse }
     * 
     */
    public ApproveReservationResponse createApproveReservationResponse() {
        return new ApproveReservationResponse();
    }

    /**
     * Create an instance of {@link AddImagesResponse }
     * 
     */
    public AddImagesResponse createAddImagesResponse() {
        return new AddImagesResponse();
    }

    /**
     * Create an instance of {@link AddPriceRequest }
     * 
     */
    public AddPriceRequest createAddPriceRequest() {
        return new AddPriceRequest();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link GetRatingResponse }
     * 
     */
    public GetRatingResponse createGetRatingResponse() {
        return new GetRatingResponse();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link MessageResponse }
     * 
     */
    public MessageResponse createMessageResponse() {
        return new MessageResponse();
    }

    /**
     * Create an instance of {@link GetReservationRequest }
     * 
     */
    public GetReservationRequest createGetReservationRequest() {
        return new GetReservationRequest();
    }

    /**
     * Create an instance of {@link AddAccommodationResponse }
     * 
     */
    public AddAccommodationResponse createAddAccommodationResponse() {
        return new AddAccommodationResponse();
    }

    /**
     * Create an instance of {@link GetMessageRequest }
     * 
     */
    public GetMessageRequest createGetMessageRequest() {
        return new GetMessageRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationTypeResponse }
     * 
     */
    public GetAccommodationTypeResponse createGetAccommodationTypeResponse() {
        return new GetAccommodationTypeResponse();
    }

    /**
     * Create an instance of {@link AccommodationType }
     * 
     */
    public AccommodationType createAccommodationType() {
        return new AccommodationType();
    }

    /**
     * Create an instance of {@link GetRecensionResponse }
     * 
     */
    public GetRecensionResponse createGetRecensionResponse() {
        return new GetRecensionResponse();
    }

    /**
     * Create an instance of {@link Recension }
     * 
     */
    public Recension createRecension() {
        return new Recension();
    }

    /**
     * Create an instance of {@link GetAgentResponse }
     * 
     */
    public GetAgentResponse createGetAgentResponse() {
        return new GetAgentResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link MessageRequest }
     * 
     */
    public MessageRequest createMessageRequest() {
        return new MessageRequest();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

}
