//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.27 at 07:05:16 PM CEST 
//


package agent.agent.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accommodation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accommodation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="agent" type="{http://www.ftn.uns.ac.rs/megatravel}user"/>
 *         &lt;element name="accommodationType" type="{http://www.ftn.uns.ac.rs/megatravel}accommodation_type"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accommodationService" type="{http://www.ftn.uns.ac.rs/megatravel}accommodation_service" maxOccurs="unbounded"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="location" type="{http://www.ftn.uns.ac.rs/megatravel}location"/>
 *         &lt;element name="accommodationId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cancelingPeriod" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="status" type="{http://www.ftn.uns.ac.rs/megatravel}accommodationStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accommodation", propOrder = {
    "agent",
    "accommodationType",
    "description",
    "accommodationService",
    "category",
    "location",
    "accommodationId",
    "capacity",
    "name",
    "cancelingPeriod",
    "status"
})
public class Accommodation {

	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="idAgent", referencedColumnName="userId")
    @XmlElement(required = true)
    protected User agent;
	
	@OneToOne
	@JoinColumn(name = "accomodation_type_id")
    @XmlElement(required = true)
    protected AccommodationType accommodationType;
    
	@XmlElement(required = true)
    protected String description;
    
	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "ACCOMMODATION_SERVICE_UNIT", 
		joinColumns= {@JoinColumn(name="accommodationId")},
		inverseJoinColumns= {@JoinColumn(name="accommodationServiceId")})
	@XmlElement(required = true)
    protected List<AccommodationService> accommodationService;
    
	protected int category;
    
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "location_id")
	@XmlElement(required = true)
    protected Location location;
    
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement(required = true)
	protected long accommodationId;
    
	protected int capacity;
    
	@XmlElement(required = true)
	protected String name;
    
	protected int cancelingPeriod;
    
	@XmlElement(required = true)
    protected AccommodationStatus status;

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setAgent(User value) {
        this.agent = value;
    }

    /**
     * Gets the value of the accommodationType property.
     * 
     * @return
     *     possible object is
     *     {@link AccommodationType }
     *     
     */
    public AccommodationType getAccommodationType() {
        return accommodationType;
    }

    /**
     * Sets the value of the accommodationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccommodationType }
     *     
     */
    public void setAccommodationType(AccommodationType value) {
        this.accommodationType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the accommodationService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accommodationService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccommodationService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccommodationService }
     * 
     * 
     */
    public List<AccommodationService> getAccommodationService() {
        if (accommodationService == null) {
            accommodationService = new ArrayList<AccommodationService>();
        }
        return this.accommodationService;
    }

    /**
     * Gets the value of the category property.
     * 
     */
    public int getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     */
    public void setCategory(int value) {
        this.category = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the accommodationId property.
     * 
     */
    public long getAccommodationId() {
        return accommodationId;
    }

    /**
     * Sets the value of the accommodationId property.
     * 
     */
    public void setAccommodationId(long value) {
        this.accommodationId = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     */
    public int getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     */
    public void setCapacity(int value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the cancelingPeriod property.
     * 
     */
    public int getCancelingPeriod() {
        return cancelingPeriod;
    }

    /**
     * Sets the value of the cancelingPeriod property.
     * 
     */
    public void setCancelingPeriod(int value) {
        this.cancelingPeriod = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link AccommodationStatus }
     *     
     */
    public AccommodationStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccommodationStatus }
     *     
     */
    public void setStatus(AccommodationStatus value) {
        this.status = value;
    }

}
