insert into user (user_id, name, surname, email, password, username, role, business_id) values (1, 'Petar', 'Petrovic', 'agent@gmail.com', '$2a$10$jChdiiMSaPYPLHj6uMATKO/40fK/xojxb8uzMjc9ACZLG/QC4PpYK', 'agent', 2, '111');
insert into accommodation_type (id, name) values (1, 'hotel');
insert into accommodation_type (id, name) values (2, 'apartman');
insert into accommodation_service (accommodation_service_id, name) values (1, 'WiFi');
insert into accommodation_service (accommodation_service_id, name) values (2, 'Parking');
insert into accommodation_service (accommodation_service_id, name) values (3, 'Dorucak');
insert into location (id, longitude, lattitude, name) values (1, 23, 44, 'location');
insert into accommodation (id_agent, accomodation_type_id, description, category, location_id, accommodation_id, capacity, name, canceling_period, status) values (1, 1, 'desc', 1, 1, 1, 3, 'name', 3, 0);
insert into accommodation (id_agent, accomodation_type_id, description, category, location_id, accommodation_id, capacity, name, canceling_period, status) values (1, 1, 'desc', 1, 1, 2, 3, 'name1', 3, 0);
insert into reservation (id, id_accommodation, id_user, from_date, to_date, status) values (1, 1, 1, '2015-05-06', '2015-05-09', 1);
insert into reservation (id, id_accommodation, id_user, from_date, to_date, status) values (2, 2, 1, '2015-05-06', '2015-05-09', 1);
insert into reservation (id, id_accommodation, id_user, from_date, to_date, status) values (3, 1, 1, '2015-05-06', '2015-05-09', 1);